import {
  Body,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Link,
  Preview,
  Section,
  Text,
} from "@react-email/components";
import type { PaperSummary } from "@/lib/types";

type SummaryEmailProps = {
  keywords: string[];
  summaries: PaperSummary[];
};

const styles = {
  body: {
    margin: "0",
    backgroundColor: "#f5f3ee",
    color: "#20201d",
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Inter, Arial, sans-serif",
  },
  container: {
    width: "100%",
    maxWidth: "680px",
    margin: "0 auto",
    padding: "34px 22px 44px",
  },
  header: {
    backgroundColor: "#fffdfa",
    border: "1px solid #ded8cd",
    borderRadius: "8px",
    padding: "26px",
  },
  kicker: {
    margin: "0 0 10px",
    color: "#b67826",
    fontSize: "12px",
    fontWeight: "700",
    letterSpacing: "0.08em",
    textTransform: "uppercase" as const,
  },
  h1: {
    margin: "0",
    color: "#20201d",
    fontSize: "30px",
    lineHeight: "1.15",
  },
  intro: {
    color: "#6f6a61",
    fontSize: "15px",
    lineHeight: "1.55",
  },
  card: {
    backgroundColor: "#fffdfa",
    border: "1px solid #ded8cd",
    borderRadius: "8px",
    marginTop: "18px",
    padding: "22px",
  },
  title: {
    margin: "0 0 12px",
    color: "#20201d",
    fontSize: "20px",
    lineHeight: "1.3",
  },
  label: {
    margin: "20px 0 6px",
    color: "#155e63",
    fontSize: "13px",
    fontWeight: "700",
  },
  text: {
    margin: "0",
    color: "#4f4a43",
    fontSize: "15px",
    lineHeight: "1.6",
  },
  item: {
    margin: "0 0 8px",
    color: "#4f4a43",
    fontSize: "15px",
    lineHeight: "1.55",
  },
  link: {
    color: "#155e63",
    fontSize: "14px",
    fontWeight: "700",
    textDecoration: "none",
  },
  footer: {
    color: "#928b80",
    fontSize: "12px",
    lineHeight: "1.5",
    marginTop: "26px",
  },
};

export default function SummaryEmail({ keywords, summaries }: SummaryEmailProps) {
  const preview =
    summaries.length === 1
      ? `Plain-language summary: ${summaries[0].title}`
      : `${summaries.length} plain-language research summaries`;

  return (
    <Html>
      <Head />
      <Preview>{preview}</Preview>
      <Body style={styles.body}>
        <Container style={styles.container}>
          <Section style={styles.header}>
            <Text style={styles.kicker}>Research Brief</Text>
            <Heading style={styles.h1}>Your education research summaries</Heading>
            <Text style={styles.intro}>
              These papers were selected from education research results for:{" "}
              <strong>{keywords.join(", ")}</strong>. Each summary is written for
              a curious non-technical reader.
            </Text>
          </Section>

          {summaries.map((summary, index) => (
            <Section key={summary.paperId} style={styles.card}>
              <Text style={styles.kicker}>Paper {index + 1}</Text>
              <Heading as="h2" style={styles.title}>
                {summary.title}
              </Heading>

              <Text style={styles.label}>Why it matters</Text>
              <Text style={styles.text}>{summary.whyItMatters}</Text>

              <Text style={styles.label}>Plain-language summary</Text>
              <Text style={styles.text}>{summary.plainLanguageSummary}</Text>

              <Text style={styles.label}>Key takeaways</Text>
              {summary.keyTakeaways.map((takeaway) => (
                <Text key={takeaway} style={styles.item}>
                  - {takeaway}
                </Text>
              ))}

              {summary.termsExplained.length > 0 ? (
                <>
                  <Text style={styles.label}>Terms explained</Text>
                  {summary.termsExplained.map((term) => (
                    <Text key={term.term} style={styles.item}>
                      <strong>{term.term}:</strong> {term.explanation}
                    </Text>
                  ))}
                </>
              ) : null}

              <Hr style={{ borderColor: "#ded8cd", margin: "20px 0" }} />
              <Link href={summary.link} style={styles.link}>
                Open the paper
              </Link>
            </Section>
          ))}

          <Text style={styles.footer}>
            Generated by Research Brief. Summaries simplify the research and
            should be treated as a starting point, not as a substitute for the
            paper.
          </Text>
        </Container>
      </Body>
    </Html>
  );
}
